# Определения типов
type Client {
  """
  Уникальный идентификатор клиента
  """
  id: ID!

  """
  Полное имя клиента
  """
  name: String

  """
  Возраст клиента
  """
  age: Int

  """
  Список документов клиента
  """
  documents: [Document!]!

  """
  Информация о родственниках клиента
  """
  relatives: [Relative!]!
}

type Document {
  """
  Уникальный идентификатор документа
  """
  id: ID!

  """
  Тип документа (паспорт, водительское удостоверение и т.д.)
  """
  type: String

  """
  Номер документа
  """
  number: String

  """
  Дата выдачи документа
  """
  issueDate: String

  """
  Дата окончания срока действия документа
  """
  expiryDate: String
}

type Relative {
  """
  Уникальный идентификатор родственника
  """
  id: ID!

  """
  Тип родственной связи (супруг, ребенок, родитель и т.д.)
  """
  relationType: String

  """
  Имя родственника
  """
  name: String

  """
  Возраст родственника
  """
  age: Int
}

# Корневой тип Query
type Query {
  """
  Получить информацию о клиенте по ID
  """
  client(id: ID!): Client

  """
  Получить список документов клиента по ID
  """
  clientDocuments(id: ID!): [Document!]!

  """
  Получить информацию о родственниках клиента по ID
  """
  clientRelatives(id: ID!): [Relative!]!
}

# Схема
schema {
  query: Query
}
